### ISSUE TITLE
Modifying indexes.

### ISSUE THREAD

**Issue by lemoer** [jue89/jmf#2]
When an index is already created and you want to modify it (e.g. make it unique), you will first have to delete the index (manually in mongo) before jmf will create the right (unique) index.

Was this behavior expected?

**Comment by jue89** [comment]
JMF just calls the ```ensureIndex()``` function of the mongodb driver. So I haven't thought about the problem before you came up with this issue ;) I don't know whether the guys working on the mongodb module are aware of this problem, too.

**Comment by lemoer** [comment]
Hm. Okay I'll simply add a note to the documentation.. ;)
